baseURL = ''
languageCode = 'en-us'
title = 'Woman in the Garage'
theme = 'ananke'

[params]
  custom_css = ["custom.css"]
  site_logo = "images/852E5D23-7B77-4084-972F-A10863D279BB.jpeg"
  background_color_class = "bg-white"
  featured_image = "/images/IMG_0680.jpeg"

[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "Episodes"
  url = "/podcasts/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "Contributors"
  url = "/authors/"
  weight = 4
