baseURL = ''
languageCode = 'en-us'
title = 'Woman in the Garage'
theme = 'ananke'

[params]
  custom_css = ["custom.css"]
  site_logo = "img/logo-transparent.png"
  background_color_class = "bg-white"
  featured_image = "/images/banner-800x400.png"

[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "Episodes"
  url = "/podcasts/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "Contributors"
  url = "/authors/"
  weight = 4
